#!/bin/sh

# Check if the development server is already running on port 3000
# 3000번 포트가 사용중인지 체크
if netstat -ano | grep -q ':3000'; then
  echo "Development server is already running on port 3000."
else
  # Start the development server in the background
  npm run dev &
  # Get the PID of the last command (npm run dev)
  DEV_SERVER_PID=$!
  
  # Wait for the server to be ready (adjust the URL and port as necessary)
# dev 환경이 될 때까지 기다리기
  wait-on http://localhost:3000
fi

# Run Cypress tests
npm run cypress

# Kill the dev server after tests are done if it was started in this script
# 백그라운드에서 실행한 3000번 포트 서버 강제 종료
if [ ! -z "$DEV_SERVER_PID" ]; then
  kill $DEV_SERVER_PID
fi
