#!/bin/sh

# Start the development server in the background
npm run dev &

# Get the PID of the last command (npm run dev)
DEV_SERVER_PID=$!

# Wait for the server to be ready (adjust the URL and port as necessary)
wait-on http://localhost:3000

# Run Cypress tests
npm run cypress

# Kill the dev server after tests are done
kill $DEV_SERVER_PID
